- name: Allow 2181
  command: ufw allow 2181/tcp 
  register: output
  become: yes

- name: Allow 9092
  command:  ufw allow 9092/tcp 
  register: output
  become: yes


- name: Allow 5984
  command:  ufw allow 5984/tcp 
  register: output
  become: yes